### ISSUE TITLE
Building storm-streaming 1.0-SNAPSHOT -  Compilation Error

### ISSUE THREAD

**Issue by dirttech** [hortonworks-gallery/iot-truck-streaming#8]
@nickcdryan I am using maven 3.2.5 on HDP 2.5 sandbox - ambari [virtualbox](url) setup and getting this error -
`
[INFO] ------------------------------------------------------------------------ 
[INFO] Building storm-streaming 1.0-SNAPSHOT 
[INFO] ------------------------------------------------------------------------ 
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ storm-streaming --- 
[INFO] Using 'UTF-8' encoding to copy filtered resources. [INFO] Copying 5 resources 
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ storm-streaming --- 
[INFO] Changes detected - recompiling the module! 
[INFO] Compiling 18 source files to /root/iot-truck-streaming/storm-streaming/target/classes 
[INFO] ------------------------------------------------------------- 
[ERROR] COMPILATION ERROR : 
[INFO] ------------------------------------------------------------- 
[ERROR] /root/iot-truck-streaming/storm-streaming/src/main/java/com/hortonworks/streaming/impl/bolts/Prediction.java:[3,28] package backtype.storm.tuple does not exist 
[ERROR] /root/iot-truck-streaming/storm-streaming/src/main/java/com/hortonworks/streaming/impl/bolts/Prediction.java:[9,11] cannot find symbol symbol: class Tuple`
`
@abajwa-hw Is it supported on HDP 2.5 now?

**Comment by abajwa-hw** [comment]
@dirttech we ran into issues getting this one to work with HDP 2.5

For 2.5, this is the version we are using but default sandbox may not have enough memory to run this:
https://github.com/sujithasankuhdp/hdp/tree/master/reference-apps/iot-trucking-app

Steps to setup on single node:
https://gist.github.com/abajwa-hw/83800881b3e1012aec5509d5591faa72

The ambari service has been updated to use this (make sure to use hdp25 branch):
https://github.com/hortonworks-gallery/iotdemo-service/tree/hdp25

However, the easiest way to get the demo up might be to use the prebuilt Amazon AMI
https://community.hortonworks.com/articles/58330/automation-to-deploy-hdp-25nifi-10-clusters-runnin.html
